import os
from dotenv import load_dotenv

load_dotenv()

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
    raise ValueError("TELEGRAM_BOT_TOKEN o TELEGRAM_CHAT_ID mancanti nel file .env")

CPU_WARNING = 70
RAM_WARNING = 70
DISK_WARNING = 70

CPU_CRITICAL = 90
RAM_CRITICAL = 90
DISK_CRITICAL = 90

CHECK_INTERVAL_SECONDS = 300